/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi;

/**
 *
 * @author raiha
 */
public class MainResto extends javax.swing.JFrame {

    /**
     * Creates new form MainResto
     */
    public MainResto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txapesan = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        MainPegawai = new javax.swing.JButton();
        MainPelanggan = new javax.swing.JButton();
        MainMenu = new javax.swing.JButton();
        MainPesanan = new javax.swing.JButton();
        MainPembayaran = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NONGKI KUY RESTO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 6, -1, 35));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        txapesan.setViewportView(jTextArea1);

        getContentPane().add(txapesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 47, 652, 394));

        MainPegawai.setText("Pegawai");
        MainPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainPegawaiActionPerformed(evt);
            }
        });
        getContentPane().add(MainPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 156, 93, 31));

        MainPelanggan.setText("Pelanggan");
        MainPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainPelangganActionPerformed(evt);
            }
        });
        getContentPane().add(MainPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 197, 93, 30));

        MainMenu.setText("Menu");
        MainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuActionPerformed(evt);
            }
        });
        getContentPane().add(MainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 115, 93, 30));

        MainPesanan.setText("Pemesanan");
        MainPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainPesananActionPerformed(evt);
            }
        });
        getContentPane().add(MainPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 280, 93, 30));

        MainPembayaran.setText("Pembayaran");
        MainPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainPembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(MainPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 238, -1, 31));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 260, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainPegawaiActionPerformed
        // TODO add your handling code here:
        Restoran Pegawai1 = new Restoran(11211053,"Adit", "Jl. Nila No.10");
        Restoran Pegawai2 = new Restoran(11211035,"Edis", "Jl. Kakap No.7");
        Restoran Pegawai3 = new Restoran(11211044,"Raihan","Jl. Baronang No.1" );
        Restoran Pegawai4 = new Restoran(11211049,"Manahati","Jl. Mujair No.8");
        
        // akses method mencatatPesanan()
        Pegawai1.mencatatPesanan();
        Pegawai2.mencatatPesanan();
        Pegawai3.mencatatPesanan();
        Pegawai4.mencatatPesanan();
        System.out.println("\n");
        
        // akses method membuatPesanan()
        Pegawai1.membuatPesanan();
        Pegawai2.membuatPesanan();
        Pegawai3.membuatPesanan();
        Pegawai4.membuatPesanan();
        
        // convert ke gui
        jTextArea1.setText("Pegawai atas nama : " + Pegawai1.nama + " (" +Pegawai1.id + ")" 
                + " tempat domisili tinggal " + Pegawai1.alamat + " mencatat pesanan pelanggan" + "\n"
                +"Pegawai atas nama : " + Pegawai2.nama + " (" +Pegawai2.id + ")" 
                + " tempat domisili tinggal " + Pegawai2.alamat + " mencatat pesanan pelanggan" + "\n"
                +"Pegawai atas nama : " + Pegawai3.nama + " (" +Pegawai3.id + ")" 
                + " tempat domisili tinggal " + Pegawai3.alamat + " mencatat pesanan pelanggan" + "\n"
                +"Pegawai atas nama : " + Pegawai4.nama + " (" +Pegawai4.id + ")" 
                + " tempat domisili tinggal " + Pegawai4.alamat + " mencatat pesanan pelanggan" + "\n\n"
                +"Pegawai atas nama : " + Pegawai1.nama + " (" +Pegawai1.id + ")" 
                + " tempat domisili tinggal " + Pegawai1.alamat + " membuat pesanan pelanggan" + "\n"
                +"Pegawai atas nama : " + Pegawai2.nama + " (" +Pegawai2.id + ")" 
                + " tempat domisili tinggal " + Pegawai2.alamat + " membuat pesanan pelanggan" + "\n"
                +"Pegawai atas nama : " + Pegawai3.nama + " (" +Pegawai3.id + ")" 
                + " tempat domisili tinggal " + Pegawai3.alamat + " membuat pesanan pelanggan" + "\n"
                +"Pegawai atas nama : " + Pegawai4.nama + " (" +Pegawai4.id + ")" 
                + " tempat domisili tinggal " + Pegawai4.alamat + " membuat pesanan pelanggan" + "\n"
                
        );
        
        
    }//GEN-LAST:event_MainPegawaiActionPerformed

    private void MainPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainPelangganActionPerformed
        // TODO add your handling code here:
        // Membuat objek pelanggan 1, pelanggan 2, pelanggan 3, pelanggan 4, pelanggan 5, pelanggan 6, pelanggan 7, pelanggan 8
        Pelanggan pelanggan1 = new Pelanggan(10001, "Iqbal", "Jl. Apel No.4");
        Pelanggan pelanggan2 = new Pelanggan(10002, "Nisa", "Jl. Nanas No.9");
        Pelanggan pelanggan3 = new Pelanggan(10003, "Nio", "Jl. Semangka No.45");
        Pelanggan pelanggan4 = new Pelanggan(10004, "Rama", "Jl. Strawberry No.33");
        Pelanggan pelanggan5 = new Pelanggan(10005, "Gerald", "Jl. Jeruk No.12");
        Pelanggan pelanggan6 = new Pelanggan(10006, "Fio", "Jl. Mangga No.6");
        Pelanggan pelanggan7 = new Pelanggan(10007, "Farel", "Jl. Manggis No.78");
        Pelanggan pelanggan8 = new Pelanggan(10008, "Julian", "Jl. Kelapa Sawit No.51");
        // pemberian nilai atribut noMeja
        pelanggan1.noMeja = 23;
        pelanggan2.noMeja = 8;
        pelanggan3.noMeja = 20;
        pelanggan4.noMeja = 6;
        pelanggan5.noMeja = 12;
        pelanggan6.noMeja = 19;
        pelanggan7.noMeja = 4;
        pelanggan8.noMeja = 22;
        // pemberian nilai atribut detail pesanan
        pelanggan1.detailPesanan = "Pemesanan dengan Kode menu 221 berupa Nasi Goreng dan Teh Hangat dengan harga Rp.20000";
        pelanggan2.detailPesanan = "Pemesanan dengan Kode menu 222 berupa Mie Goreng dan Orange Juice dengan harga Rp.22000";
        pelanggan3.detailPesanan = "Pemesanan dengan Kode menu 223 berupa Mie Ayam dan Ice Lemon Tea dengan harga Rp.24000";
        pelanggan4.detailPesanan = "Pemesanan dengan Kode menu 224 berupa Bakso dan Ice Melon dengan harga Rp.25000";
        pelanggan5.detailPesanan = "Pemesanan dengan Kode menu 225 berupa Soto dan Ice Tea dengan harga Rp.21000";
        pelanggan6.detailPesanan = "Pemesanan dengan Kode menu 221 berupa Nasi Goreng dan Teh Hangat dengan harga Rp.20000";
        pelanggan7.detailPesanan = "Pemesanan dengan Kode menu 222 berupa Mie Goreng dan Orange Juice dengan harga Rp.22000";
        pelanggan8.detailPesanan = "Pemesanan dengan Kode menu 223 berupa Mie Ayam dan Ice Lemon Tea dengan harga Rp.24000";

        // Pemberian nilai pembayaran pada pelanggan 1-8
        pelanggan1.pembayaran = 20000;
        pelanggan2.pembayaran = 22000;
        pelanggan3.pembayaran = 24000;
        pelanggan4.pembayaran = 25000;
        pelanggan5.pembayaran = 21000;
        pelanggan6.pembayaran = 20000;
        pelanggan7.pembayaran = 22000;
        pelanggan8.pembayaran = 24000;
        
        // convert ke gui
        jTextArea1.setText("Pelanggan atas nama : " + pelanggan1.nama + " (" + pelanggan1.id + ")" 
                + " No meja " + pelanggan1.noMeja + " sedang melihat menu \n"
                + "Pelanggan atas nama : " + pelanggan2.nama + " (" + pelanggan2.id + ")" 
                + " No meja " + pelanggan2.noMeja + " sedang melihat menu \n"
                + "Pelanggan atas nama : " + pelanggan3.nama + " (" + pelanggan3.id + ")" 
                + " No meja " + pelanggan3.noMeja + " sedang melihat menu \n"
                + "Pelanggan atas nama : " + pelanggan4.nama + " (" + pelanggan4.id + ")" 
                + " No meja " + pelanggan4.noMeja + " sedang melihat menu \n"
                + "Pelanggan atas nama : " + pelanggan5.nama + " (" + pelanggan5.id + ")" 
                + " No meja " + pelanggan5.noMeja + " sedang melihat menu \n"
                + "Pelanggan atas nama : " + pelanggan6.nama + " (" + pelanggan6.id + ")" 
                + " No meja " + pelanggan6.noMeja + " sedang melihat menu \n"
                + "Pelanggan atas nama : " + pelanggan7.nama + " (" + pelanggan7.id + ")" 
                + " No meja " + pelanggan7.noMeja + " sedang melihat menu \n"
                + "Pelanggan atas nama : " + pelanggan8.nama + " (" + pelanggan8.id + ")" 
                + " No meja " + pelanggan8.noMeja + " sedang melihat menu \n\n ============================= \n\n"
                + "Pelanggan atas nama : " + pelanggan1.nama + " (" + pelanggan1.id + ")" 
                + " No meja " + pelanggan1.noMeja + " memilih menu berupa \n" + pelanggan1.detailPesanan + "\n\n"
                + "Pelanggan atas nama : " + pelanggan2.nama + " (" + pelanggan2.id + ")" 
                + " No meja " + pelanggan2.noMeja + " memilih menu berupa \n" + pelanggan2.detailPesanan + "\n\n"
                + "Pelanggan atas nama : " + pelanggan3.nama + " (" + pelanggan3.id + ")" 
                + " No meja " + pelanggan3.noMeja + " memilih menu berupa \n" + pelanggan3.detailPesanan + "\n\n"
                + "Pelanggan atas nama : " + pelanggan4.nama + " (" + pelanggan4.id + ")" 
                + " No meja " + pelanggan4.noMeja + " memilih menu berupa \n" + pelanggan4.detailPesanan + "\n\n"
                + "Pelanggan atas nama : " + pelanggan5.nama + " (" + pelanggan5.id + ")" 
                + " No meja " + pelanggan5.noMeja + " memilih menu berupa \n" + pelanggan5.detailPesanan + "\n\n"
                + "Pelanggan atas nama : " + pelanggan6.nama + " (" + pelanggan6.id + ")" 
                + " No meja " + pelanggan6.noMeja + " memilih menu berupa \n" + pelanggan6.detailPesanan + "\n\n"
                + "Pelanggan atas nama : " + pelanggan7.nama + " (" + pelanggan7.id + ")" 
                + " No meja " + pelanggan7.noMeja + " memilih menu berupa \n" + pelanggan7.detailPesanan + "\n\n"
                + "Pelanggan atas nama : " + pelanggan8.nama + " (" + pelanggan8.id + ")" 
                + " No meja " + pelanggan8.noMeja + " memilih menu berupa \n" + pelanggan8.detailPesanan + "\n\n "
                        + "============================= \n\n"
                + "Pelanggan atas nama : " + pelanggan1.nama + " (" +pelanggan1.id + ") domisili tinggal " 
                + pelanggan1.alamat + " No meja " + pelanggan1.noMeja + " \nmembayar pesanan sebesar Rp." + pelanggan1.pembayaran + "\n\n"
                + "Pelanggan atas nama : " + pelanggan2.nama + " (" +pelanggan2.id + ") domisili tinggal " 
                + pelanggan2.alamat + " No meja " + pelanggan2.noMeja + " \nmembayar pesanan sebesar " + pelanggan2.pembayaran + "\n\n"
                + "Pelanggan atas nama : " + pelanggan3.nama + " (" +pelanggan3.id + ") domisili tinggal " 
                + pelanggan3.alamat + " No meja " + pelanggan3.noMeja + " \nmembayar pesanan sebesar Rp." + pelanggan3.pembayaran + "\n\n"
                + "Pelanggan atas nama : " + pelanggan4.nama + " (" +pelanggan4.id + ") domisili tinggal " 
                + pelanggan4.alamat + " No meja " + pelanggan4.noMeja + " \nmembayar pesanan sebesar Rp." + pelanggan4.pembayaran + "\n\n"
                + "Pelanggan atas nama : " + pelanggan5.nama + " (" +pelanggan5.id + ") domisili tinggal " 
                + pelanggan5.alamat + " No meja " + pelanggan5.noMeja + " \nmembayar pesanan sebesar Rp." + pelanggan5.pembayaran + "\n\n"
                + "Pelanggan atas nama : " + pelanggan6.nama + " (" +pelanggan6.id + ") domisili tinggal " 
                + pelanggan6.alamat + " No meja " + pelanggan6.noMeja + " \nmembayar pesanan sebesar Rp." + pelanggan6.pembayaran + "\n\n"
                + "Pelanggan atas nama : " + pelanggan7.nama + " (" +pelanggan7.id + ") domisili tinggal " 
                + pelanggan7.alamat + " No meja " + pelanggan7.noMeja + " \nmembayar pesanan sebesar Rp." + pelanggan7.pembayaran + "\n\n"
                + "Pelanggan atas nama : " + pelanggan8.nama + " (" +pelanggan8.id + ") domisili tinggal " 
                + pelanggan8.alamat + " No meja " + pelanggan8.noMeja + " \nmembayar pesanan sebesar Rp." + pelanggan8.pembayaran
        );
    
        
    }//GEN-LAST:event_MainPelangganActionPerformed

    private void MainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuActionPerformed
        // TODO add your handling code here:
        // membuat objek menu 1, menu 2, menu 3, menu 4, dan menu 5
        Menu menu1 = new Menu("Nasi Goreng", "Teh Hangat", 20000);
        Menu menu2 = new Menu("Mie Goreng", "Orange Juice", 22000);
        Menu menu3 = new Menu("Mie Ayam", "Ice Lemon Tea", 24000);
        Menu menu4 = new Menu("Bakso", "Ice Melon", 25000);
        Menu menu5 = new Menu("Soto", "Ice Tea", 21000);
        
        // pemberian nilai atribut kode menu
        menu1.kodeMenu = 221;
        menu2.kodeMenu = 222;
        menu3.kodeMenu = 223;
        menu4.kodeMenu = 224;
        menu5.kodeMenu = 225;
        
        // akses method add()
        menu1.menampilkanMenu();
        menu2.menampilkanMenu();
        menu3.menampilkanMenu();
        menu4.menampilkanMenu();
        menu5.menampilkanMenu();
        System.out.println("\n");
        
        // akses method updated()
        menu1.menampilkanHarga();
        menu2.menampilkanHarga();
        menu3.menampilkanHarga();
        menu4.menampilkanHarga();
        menu5.menampilkanHarga();
       
        // convert ke gui
        jTextArea1.setText("Kode menu " + Integer.toString(menu1.kodeMenu) + " berupa " + menu1.makanan 
                + " dan " + menu1.minuman + "\n" 
                + "Kode menu " + Integer.toString(menu2.kodeMenu) + " berupa " + menu2.makanan 
                + " dan " + menu2.minuman + "\n" 
                + "Kode menu " + Integer.toString(menu3.kodeMenu) + " berupa " + menu3.makanan 
                + " dan " + menu3.minuman + "\n" 
                + "Kode menu " + Integer.toString(menu4.kodeMenu) + " berupa " + menu4.makanan 
                + " dan " + menu4.minuman + "\n" 
                + "Kode menu " + Integer.toString(menu5.kodeMenu) + " berupa " + menu5.makanan 
                + " dan " + menu5.minuman + "\n\n"
                + "Kode menu " + Integer.toString(menu1.kodeMenu) + " Rp." + Integer.toString(menu1.harga) + "\n"
                + "Kode menu " + Integer.toString(menu2.kodeMenu) + " Rp." + Integer.toString(menu2.harga) + "\n"
                + "Kode menu " + Integer.toString(menu3.kodeMenu) + " Rp." + Integer.toString(menu3.harga) + "\n"
                + "Kode menu " + Integer.toString(menu4.kodeMenu) + " Rp." + Integer.toString(menu4.harga) + "\n"
                + "Kode menu " + Integer.toString(menu5.kodeMenu) + " Rp." + Integer.toString(menu5.harga) + "\n"
        );
    }//GEN-LAST:event_MainMenuActionPerformed

    private void MainPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainPembayaranActionPerformed
        // TODO add your handling code here:
        // membuat objek pembayaran oleh penggan 1 sampai 8
        Pembayaran pembayaranPelanggan1 = new Pembayaran(23,"Nasi Goreng, Teh Hangat", 20000);
        Pembayaran pembayaranPelanggan2 = new Pembayaran(8,"Mie Goreng, Orange Juice" ,22000);
        Pembayaran pembayaranPelanggan3 = new Pembayaran(20,"Mie Ayam, Ice Lemon Tea" ,24000);
        Pembayaran pembayaranPelanggan4 = new Pembayaran(6,"Bakso, Ice Melon" ,25000);
        Pembayaran pembayaranPelanggan5 = new Pembayaran(12,"Soto, Ice Tea" ,21000);
        Pembayaran pembayaranPelanggan6 = new Pembayaran(19,"Nasi Goreng, Teh Hangat" ,20000);
        Pembayaran pembayaranPelanggan7 = new Pembayaran(4,"Mie Goreng, Orange Juice" ,22000);
        Pembayaran pembayaranPelanggan8 = new Pembayaran(22,"Mie Ayam , Ice Lemon Tea" ,24000);
        
        // akses method update
        pembayaranPelanggan1.transaksi();
        pembayaranPelanggan2.transaksi();
        pembayaranPelanggan3.transaksi();
        pembayaranPelanggan4.transaksi();
        pembayaranPelanggan5.transaksi();
        pembayaranPelanggan6.transaksi();
        pembayaranPelanggan7.transaksi();
        pembayaranPelanggan8.transaksi();
        
        // akses ke gui
        jTextArea1.setText("Pembayaran Pelanggan no meja " + pembayaranPelanggan1.noMeja 
                + "\nberupa " + pembayaranPelanggan1.menu + " dengan total harga Rp." 
                + pembayaranPelanggan1.totalHarga + " sukses \n\n ========================= \n\n"
                + "Pembayaran Pelanggan no meja " + pembayaranPelanggan2.noMeja 
                + "\nberupa " + pembayaranPelanggan2.menu + " dengan total harga Rp." 
                + pembayaranPelanggan2.totalHarga + " sukses \n\n ========================= \n\n"
                + "Pembayaran Pelanggan no meja " + pembayaranPelanggan3.noMeja 
                + "\nberupa " + pembayaranPelanggan3.menu + " dengan total harga Rp." 
                + pembayaranPelanggan3.totalHarga + " sukses \n\n ========================= \n\n"
                + "Pembayaran Pelanggan no meja " + pembayaranPelanggan4.noMeja 
                + "\nberupa " + pembayaranPelanggan4.menu + " dengan total harga Rp." 
                + pembayaranPelanggan4.totalHarga + " sukses \n\n ========================= \n\n"
                + "Pembayaran Pelanggan no meja " + pembayaranPelanggan5.noMeja 
                + "\nberupa " + pembayaranPelanggan5.menu + " dengan total harga Rp." 
                + pembayaranPelanggan5.totalHarga + " sukses \n\n ========================= \n\n"
                + "Pembayaran Pelanggan no meja " + pembayaranPelanggan6.noMeja 
                + "\nberupa " + pembayaranPelanggan6.menu + " dengan total harga Rp." 
                + pembayaranPelanggan6.totalHarga + " sukses \n\n ========================= \n\n"
                + "Pembayaran Pelanggan no meja " + pembayaranPelanggan7.noMeja 
                + "\nberupa " + pembayaranPelanggan7.menu + " dengan total harga Rp." 
                + pembayaranPelanggan7.totalHarga + " sukses \n\n ========================= \n\n"
                + "Pembayaran Pelanggan no meja " + pembayaranPelanggan8.noMeja 
                + "\nberupa " + pembayaranPelanggan8.menu + " dengan total harga Rp." 
                + pembayaranPelanggan8.totalHarga + " sukses \n\n ========================= \n\n"
        );
        
        
        
        
    }//GEN-LAST:event_MainPembayaranActionPerformed

    private void MainPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainPesananActionPerformed
        // TODO add your handling code here:
        //membuat objek pemesanan dari pelanggan 1 sampai 8
        Pemesanan pemesananPelanggan1 = new Pemesanan(23, "Pemesanan dengan Kode menu 221 berupa Nasi Goreng dan Teh", 20000);
        Pemesanan pemesananPelanggan2 = new Pemesanan(8, "Pemesanan dengan Kode menu 222 berupa Mie Goreng dan Orange Juice", 22000);
        Pemesanan pemesananPelanggan3 = new Pemesanan(20, "Pemesanan dengan Kode menu 223 berupa Mie Ayam dan Ice Lemon Tea", 24000);
        Pemesanan pemesananPelanggan4 = new Pemesanan(6, "Pemesanan dengan Kode menu 224 berupa Bakso dan Ice Melon", 25000);
        Pemesanan pemesananPelanggan5 = new Pemesanan(12, "Pemesanan dengan Kode menu 225 berupa Soto dan Ice Tea", 21000);
        Pemesanan pemesananPelanggan6 = new Pemesanan(19, "Pemesanan dengan Kode menu 221 berupa Nasi Goreng dan Teh", 20000);
        Pemesanan pemesananPelanggan7 = new Pemesanan(4, "Pemesanan dengan Kode menu 222 berupa Mie Goreng dan Orange Juice", 22000);
        Pemesanan pemesananPelanggan8 = new Pemesanan(22, "Pemesanan dengan Kode menu 223 berupa Mie Ayam dan Ice Lemon Tea", 24000);
        
        // akses method menampilkanStruk()
        pemesananPelanggan1.menampilkanStruk();
        pemesananPelanggan2.menampilkanStruk();
        pemesananPelanggan3.menampilkanStruk();
        pemesananPelanggan4.menampilkanStruk();
        pemesananPelanggan5.menampilkanStruk();
        pemesananPelanggan6.menampilkanStruk();
        pemesananPelanggan7.menampilkanStruk();
        pemesananPelanggan8.menampilkanStruk();
        
        // akses ke gui
        jTextArea1.setText("struk Pemesanan kepada Pelanggan pada no meja " + pemesananPelanggan1.noMeja 
                + "\n" + pemesananPelanggan1.detailPesanan + " dengan total harga " + "Rp." + pemesananPelanggan1.pembayaran 
                + "\n\n ========================= \n\n"
                + "struk Pemesanan kepada Pelanggan pada no meja " + pemesananPelanggan2.noMeja 
                + "\n" + pemesananPelanggan2.detailPesanan + " dengan total harga " + "Rp." + pemesananPelanggan2.pembayaran 
                + "\n\n ========================= \n\n"
                + "struk Pemesanan kepada Pelanggan pada no meja " + pemesananPelanggan3.noMeja 
                + "\n" + pemesananPelanggan3.detailPesanan + " dengan total harga " + "Rp." + pemesananPelanggan3.pembayaran 
                + "\n\n ========================= \n\n"
                + "struk Pemesanan kepada Pelanggan pada no meja " + pemesananPelanggan4.noMeja 
                + "\n" + pemesananPelanggan4.detailPesanan + " dengan total harga " + "Rp." + pemesananPelanggan4.pembayaran 
                + "\n\n ========================= \n\n"
                + "struk Pemesanan kepada Pelanggan pada no meja " + pemesananPelanggan5.noMeja 
                + "\n" + pemesananPelanggan5.detailPesanan + " dengan total harga " + "Rp." + pemesananPelanggan5.pembayaran 
                + "\n\n ========================= \n\n"
                + "struk Pemesanan kepada Pelanggan pada no meja " + pemesananPelanggan6.noMeja 
                + "\n" + pemesananPelanggan6.detailPesanan + " dengan total harga " + "Rp." + pemesananPelanggan6.pembayaran 
                + "\n\n ========================= \n\n"
                + "struk Pemesanan kepada Pelanggan pada no meja " + pemesananPelanggan7.noMeja 
                + "\n" + pemesananPelanggan7.detailPesanan + " dengan total harga " + "Rp." + pemesananPelanggan7.pembayaran 
                + "\n\n ========================= \n\n"
                + "struk Pemesanan kepada Pelanggan pada no meja " + pemesananPelanggan8.noMeja 
                + "\n" + pemesananPelanggan8.detailPesanan + " dengan total harga " + "Rp." + pemesananPelanggan8.pembayaran 
                + "\n\n ========================= \n\n"
        
        );
    }//GEN-LAST:event_MainPesananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainResto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainResto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainResto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainResto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainResto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MainMenu;
    private javax.swing.JButton MainPegawai;
    private javax.swing.JButton MainPelanggan;
    private javax.swing.JButton MainPembayaran;
    private javax.swing.JButton MainPesanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JScrollPane txapesan;
    // End of variables declaration//GEN-END:variables
}
